common_words = {
    "the", "and", "a", "in", "to", "of", "that", "is", "it", "on", "for", "as", 
    "was", "with", "by", "an", "be", "this", "or", "from", "but", "are", "at", 
    "which", "not", "have", "were", "has", "had", "they", "you", "we", "he", 
    "she", "his", "her", "its", "i", "their", "all", "can", "if", "do", "does", 
    "did", "will", "would", "there", "so", "up", "out", "about", "what", "when", 
    "where", "how", "why", "then", "than", "just", "could", "should", "may", 
    "must", "might", "being", "like", "one", "only", "some", "other", "any", 
    "my", "your", "our", "me", "them", "more", "such", "these", "those", "now", 
    "here", "over", "under", "new", "used", "use", "who", "also", "many", "very", 
    "each", "every", "same", "few", "again", "off", "own", "page", "pages", 
    "website", "site", "web", "please", "click", "cookies", "privacy", "policy", 
    "terms", "conditions", "title", "home", "contact", "about", "support", 
    "service", "services", "help", "account", "login", "signup", "search", 
    "results", "news", "latest", "content", "related", "read", "view", "submit", 
    "comments", "share", "like", "follow", "subscribe", "username", "password", 
    "welcome", "message", "email", "address", "form", "list", "data", "file", 
    "terms", "agreement", "button", "settings", "dashboard", "details", 
    "information", "name", "info", "menu", "section", "form", "submit", 
    "read", "next", "previous", "back", "footer", "header", "navigation", 
    "advertisement", "social", "media", "post", "reply", "login", "user", 
    "document", "please", "click", "agree", "decline", "accept", "more", 
    "less", "recent", "update", "last", "first", "current", "feedback", 
    "error", "report", "issue", "successful", "redirect", "loading", 
    "error", "timeout", "subscribe", "unsubscribe", "advertising", 
    "description", "keyword", "metadata", "icon", "sitemap", "robots",
    "link", "para", "todos"
}
